name: post-release

on:
  release:
    types:
      - published

jobs:
  retag-lifecycle-images-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Set env
        run: |
          echo "::set-env name=LIFECYCLE_VERSION::$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f2)"
          echo "::set-env name=LIFECYCLE_IMAGE_TAG::$(git describe --always --dirty)"
      - name: Retag release candidate lifecycle images
        run: |
          docker pull yaelharel/lifecycle:${LIFECYCLE_IMAGE_TAG}-linux
          docker image tag yaelharel/lifecycle:${LIFECYCLE_IMAGE_TAG}-linux yaelharel/lifecycle:${LIFECYCLE_VERSION}-linux
          docker image tag yaelharel/lifecycle:${LIFECYCLE_IMAGE_TAG}-linux yaelharel/lifecycle:latest-linux
          docker push yaelharel/lifecycle:${LIFECYCLE_VERSION}-linux
          docker push yaelharel/lifecycle:latest-linux
retag-lifecycle-images-windows:
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set env
      run: |
        echo "::set-env name=LIFECYCLE_VERSION::$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f2)"
        echo "::set-env name=LIFECYCLE_IMAGE_TAG::$(git describe --always --dirty)"
    - name: Retag release candidate lifecycle images
      run: |
        docker pull yaelharel/lifecycle:${LIFECYCLE_IMAGE_TAG}-windows
        docker image tag yaelharel/lifecycle:${LIFECYCLE_IMAGE_TAG}-windows yaelharel/lifecycle:${LIFECYCLE_VERSION}-windows
        docker image tag yaelharel/lifecycle:${LIFECYCLE_IMAGE_TAG}-windows yaelharel/lifecycle:latest-windows
        docker push yaelharel/lifecycle:${LIFECYCLE_VERSION}-windows
        docker push yaelharel/lifecycle:latest-windows
create-manifest-lists:
  runs-on: ubuntu-latest
  needs: [retag-lifecycle-images-linux, retag-lifecycle-images-windows]
  steps:
    - name: Docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set env
      run: |
        echo "::set-env name=LIFECYCLE_VERSION::$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f2)"
    - name: Create lifecycle image manifest lists
      run: |
        DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create yaelharel/lifecycle:${LIFECYCLE_VERSION} yaelharel/lifecycle:${LIFECYCLE_VERSION}-linux yaelharel/lifecycle:${LIFECYCLE_VERSION}-windows
        DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push yaelharel/lifecycle:${LIFECYCLE_VERSION}
        DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create yaelharel/lifecycle:latest yaelharel/lifecycle:latest-linux yaelharel/lifecycle:latest-windows
        DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push yaelharel/lifecycle:latest
