name: release

on:
  workflow_dispatch:

jobs:
  test-and-build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Set up go env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: Derive lifecycle version from branch name
        run: |
          [[ $GITHUB_REF =~ ^refs\/heads\/release/(.*)$ ]] && version=${BASH_REMATCH[1]}
          if [[ -z "${version}" ]]; then
            echo "lifecycle version not detected."
            exit 1
          fi
          echo "::set-env name=LIFECYCLE_VERSION::$version"
        shell: bash
      - name: Install jq
        run: |
          mkdir -p deps/bin
          curl -s -L -o deps/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x deps/bin/jq
          echo "::add-path::${PWD}/deps/bin"
      #- name: Test
      #  run: make test
      - name: Build
        run: |
          make build-linux
          make package-linux
      - uses: actions/upload-artifact@v2
        with:
          name: lifecycle-linux-x86-64
          path: out/lifecycle-v*+linux.x86-64.tgz
  test-and-build-windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF and symlinks
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.symlinks true
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Derive lifecycle version from branch name
        run: |
          [[ $GITHUB_REF =~ ^refs\/heads\/release/(.*)$ ]] && version=${BASH_REMATCH[1]}
          if [[ -z "${version}" ]]; then
            echo "lifecycle version not detected."
            exit 1
          fi
          echo "::set-env name=LIFECYCLE_VERSION::$version"
        shell: bash
      - name: Install jq
        run: choco install jq
      #- name: Test
      #  run: make test
      #  shell: cmd
      - name: Build
        run: |
          make build-windows
          make package-windows
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: lifecycle-windows-x86-64
          path: out/lifecycle-v*+windows.x86-64.tgz
  build-lifecycle-image-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Publish to Registry
        run: |
          LIFECYCLE_VERSION=`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`
          curl -o lifecycle.tgz -L https://github.com/buildpacks/lifecycle/releases/download/v${LIFECYCLE_VERSION}/lifecycle-v${LIFECYCLE_VERSION}+linux.x86-64.tgz
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          go run ./tools/image/main.go -lifecyclePath ./lifecycle.tgz -tag buildpacksio/lifecycle:${LIFECYCLE_VERSION}-linux -tag buildpacksio/lifecycle:latest-linux
  build-lifecycle-image-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Publish to Registry
        run: |
          $LIFECYCLE_VERSION=$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f2)
          curl -o lifecycle.tgz -L https://github.com/buildpacks/lifecycle/releases/download/v${LIFECYCLE_VERSION}/lifecycle-v${LIFECYCLE_VERSION}+windows.x86-64.tgz
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          go run ./tools/image/main.go -lifecyclePath ./lifecycle.tgz -tag buildpacksio/lifecycle:${LIFECYCLE_VERSION}-windows -tag buildpacksio/lifecycle:latest-windows
  create-lifecycle-image-manifest-list:
    needs:
      - build-lifecycle-image-linux
      - build-lifecycle-image-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Manifest List
        run: |
          LIFECYCLE_VERSION=`echo ${{ github.event.release.tag_name }} | cut -d "v" -f2`
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create buildpacksio/lifecycle:${LIFECYCLE_VERSION} buildpacksio/lifecycle:${LIFECYCLE_VERSION}-linux buildpacksio/lifecycle:${LIFECYCLE_VERSION}-windows
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push buildpacksio/lifecycle:${LIFECYCLE_VERSION}
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create buildpacksio/lifecycle:latest buildpacksio/lifecycle:latest-linux buildpacksio/lifecycle:latest-windows
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push buildpacksio/lifecycle:latest
  release:
    needs:
      - test-and-build-linux
      - test-and-build-windows
      - build-lifecycle-image-linux
      - build-lifecycle-image-windows
      - create-lifecycle-image-manifest-list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Derive lifecycle version from branch name
        run: |
          [[ $GITHUB_REF =~ ^refs\/heads\/release/(.*)$ ]] && version=${BASH_REMATCH[1]}
          if [[ -z "${version}" ]]; then
            echo "lifecycle version not detected."
            exit 1
          fi
          echo "::set-env name=LIFECYCLE_VERSION::$version"
        shell: bash
      - name: Download artifacts - linux
        uses: actions/download-artifact@v1
        with:
          name: lifecycle-linux-x86-64
      - name: Download artifacts - windows
        uses: actions/download-artifact@v1
        with:
          name: lifecycle-windows-x86-64
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.LIFECYCLE_VERSION }}
          release_name: lifecycle v${{ env.LIFECYCLE_VERSION }}
          draft: true
          prerelease: false
          body: |
            # lifecycle v${{ env.LIFECYCLE_VERSION }}

            Welcome to `v${{ env.LIFECYCLE_VERSION }}`, a **beta** release of the Cloud Native Buildpack Lifecycle.

            ##  Prerequisites

            The lifecycle runs as a normal user in a series of unprivileged containers. To export images and cache image layers, it requires access to a Docker daemon **or** Docker registry.

            ## Install

            Extract the `.tgz` file and copy the lifecycle binaries into a [build stack base image](https://github.com/buildpack/spec/blob/master/platform.md#stacks). The build image can then be orchestrated by a platform implementation such as the [pack CLI](https://github.com/buildpack/pack) or [tekton](https://github.com/tektoncd/catalog/blob/master/buildpacks/README.md).
      - name: Upload Release Asset - linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lifecycle-linux-x86-64/lifecycle-v${{ env.LIFECYCLE_VERSION }}+linux.x86-64.tgz
          asset_name: lifecycle-v${{ env.LIFECYCLE_VERSION }}+linux.x86-64.tgz
          asset_content_type: application/gzip
      - name: Upload Release Asset - windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lifecycle-windows-x86-64/lifecycle-v${{ env.LIFECYCLE_VERSION }}+windows.x86-64.tgz
          asset_name: lifecycle-v${{ env.LIFECYCLE_VERSION }}+windows.x86-64.tgz
          asset_content_type: application/gzip
